[package]
authors = ["nc <mynameisnikitablack@gmail.com>"]
edition = "2018"
name = "vulkan_utils"
version = "0.1.0"

[dependencies]
ash = "0.35.1"
gpu-allocator = "0.16.0"
log = "0.4"
scopeguard = "1.1.0"
